### ISSUE TITLE
Add yolo v3/4

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/lightning-bolts#22]
https://github.com/eriklindernoren/PyTorch-YOLOv3/issues/487
https://github.com/Tianxiaomo/pytorch-YOLOv4

**Comment by OrthoDex** [comment]
Hello! I'd like to take this up!

**Comment by ananyahjha93** [comment]
@OrthoDex Have a go at it! We would welcome this contribution from your side. Do go through our contributing guidelines before you submit a PR. (https://pytorch-lightning.readthedocs.io/en/latest/CONTRIBUTING.html)

**Comment by threefoldo** [comment]
I'm also interested. @OrthoDex Will you publish your code while it's incomplete?

Beside yolo, I also want to rewrite OCR models in lightning.

**Comment by ananyahjha93** [comment]
@OrthoDex any updates on this?

**Comment by OrthoDex** [comment]
Hey @ananyahjha93, I'll aim to put up a PR sometime this weekend!

**Comment by romesco** [comment]
@OrthoDex A group in my lab is about to start doing this. Would love to have your PR as a starting point instead of duplicating efforts =].

**Comment by senarvi** [comment]
I created a [pull request](https://github.com/PyTorchLightning/pytorch-lightning-bolts/pull/552) of my YOLO implementation, which my employer [Groke Technologies](https://github.com/groke-technologies) authorized to contribute to PyTorch Lightning. It was quite difficult to get it right, since many details can only be found from the different versions of the Darknet C++ implementation (and many details are incorrect in the various PyTorch implementations). So if any of you know the YOLO architecture well, it would be great if you could check if you think that I've made any mistakes.
