### ISSUE TITLE
restructure

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/lightning-bolts#538]
## 🚀 Feature

re-think internal Bolts structure

### Motivation

ATM the structure is quite deep and very clear, my proposal is instead of actual:
```
pl_bolts
   |- callbacks
   |- models
   ...
```
move all a bit upstream
```
pl_callbacks
pl_models
...
```
but still will remain in this repo and within the same pip package

### Pitch

eventually, we could adjust installation to install just one of these or refine extras to support only selected domain-like 
`pip install pytorch-lightning-bolts[callbacks,vision]`

### Additional context

...

**Comment by akihironitta** [comment]
Would import statements change from something like `from pl_bolts.models.gans import GAN` to `from pl_models.gans import GAN`?

**Comment by Borda** [comment]
> Would import statements change from something like `from pl_bolts.models.gans import GAN` to `from pl_models.gans import GAN`?

yes, basically the main (only) difference for the user would the importing...

**Comment by oke-aditya** [comment]
I think such refactor will be nice but I do have few doubts. 

What happens to components? I think if we could solve that issue with this it would be nice. If we could cut components and layers well we can offer them as API and avoid reduplication of code (components are becoming far too many)

```
...
pl_models
------- components
------- layers
------- vision
----------- detection
----------- segmentation (maybe soon)
----------- gans
----------- self_supervised
------- ml (lets drop classical word?)
------- rl
------- text (in future)
------- audio (in future)
pl_callbacks
pl_losses
pl_metrics
pl_hub (connecting torch hub to pl)
```

I am still not clear what will be under `pl_models.vision` since any vision model possibly comes under detection, segmentation, generation or classification (most cases). Hence we can group them under `vision`. Having both vision and the categories above seems to he confusing. Above structure will make a few extensions to text, audio with simply adding folders called `text` and `audio` in `pl_models`

I'm still slightly confused about imports.
If user does simply `pip install pl_bolts` 

I think they will be

`from pl_bolts.pl_models.vision import something `

Let me know if it's wrong. In my opinion we should use `pl_` only once.

**Comment by Borda** [comment]
> Let me know if it's wrong. In my opinion we should use `pl_` only once.

yes, just to level
to GANs and SSL I do not think they are vision only so I would make them on the same level

**Comment by oke-aditya** [comment]
May I know why do you think so that GANs and Self supervised aren't under vision. 

We currently have these models only for computer vision purposes.

Also text and audio can be again separately structured in their folder as above.
