### ISSUE TITLE
UNet not corresponding to the original paper

### ISSUE THREAD

**Issue by Nora-Go** [PyTorchLightning/lightning-bolts#545]
In the original paper (U-Net: Convolutional Networks for Biomedical Image Segmentation) it is stated that "the expansive path consists of an upsampling of the feature map followed by a 2x2 convolution (“up-convolution”) that halves the number of feature channels".
In line 108 of your implementation, the kernel size is however 1 instead of two.

Moreover, the paper does not use padding, but valid convolution and crops the feature maps that are used in the skip connections. This of course leads to an output that is smaller than the input.

Also you might consider setting the bilinear parameter to True as default (as this is how the original paper up-sampled).

If you were not aiming to replicate the original UNet but instead a newer version or something please ignore my issue :)

**Comment by oke-aditya** [comment]
Hi @Nora-Go ! 

I will have a look once at all the above points for U Net. 

But this brings us to a great and new question. Reproducibility. 

Some of the models here such as FRCNN too might not match almost exactly as original paper. This difference is almost always found in every reimplemention. These might be at times due to torchvision dependency, performance or simply subtle differences like bilinear upscaling vs conv transpose 2d or kernel size 1x1 vs flatten.

Also
torchvision does not use rensnets with 3x3 first convolution layer. But reusing torchvision makes it easier. Or transforms are not applied on object detection, don't have probability parameter like albumentations. 

@akihironitta @Borda in general what should we aim for. Since all aren't quite possible. If we depend on PyTorch domain libraries C++ extension are easy. Prototyping is consistent and less to worry, test. But we have to live with these caveats at places.

**Comment by Nora-Go** [comment]
Hi :)

I totally see the reason in the changes you made (they are in most other implementations for a reason as well).
However, you are correct my issue is somehow with the reproducibility. My suggestion would be to mention all changes that were done in the code and in the doc and stick with the version you already have.

**Comment by akihironitta** [comment]
@Nora-Go Thanks for the issue! As @oke-aditya mentioned, I think this is about reproducibility. In general, I think models should be the exact same architectures as the original ones in papers for reproducibility, but for high-level models including `FasterRCNN`, it is almost impossible to match models implemented here with the original ones in papers while, for example, we heavily depend on components in external packages like `torchvision`. However, we can still follow the original implementation of `UNet` since it's quite straightforward to follow the paper's original one. We could also add args to `UNet` to control the architecture like if it uses padding or not with the default value set the same as the paper.

> torchvision does not use rensnets with 3x3 first convolution layer. 

@oke-aditya I didn't know that! I've learnt a new thing again from you :) This line, right? https://github.com/pytorch/vision/blob/09ce6758ad6ab3177f3fdec3b1bb7c7033b16712/torchvision/models/resnet.py#L173

cc: @PyTorchLightning/bolts-contributors
